package usb

const DESC_HEADER_LENGTH = 2
const DEVICE_DESC_LENGTH = 18
const CONFIG_DESC_LENGTH = 9
const INTERFACE_DESC_LENGTH = 9
const ENDPOINT_DESC_LENGTH = 7
const ENDPOINT_AUDIO_DESC_LENGTH = 9
